project_id = "shaennolzacbbagyzhoe"

[functions.extract-students]
verify_jwt = false

[functions.analyze-grading-template]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.process-subscription-emails]
verify_jwt = false

[functions.send-broadcast-email]
verify_jwt = false
